# Generated by Django 4.0.2 on 2023-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='customername',
            field=models.CharField(max_length=50),
        ),
    ]
